version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    secrets:
      - api_key
      - base_uri
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

secrets:
  api_key:
    external: true
  base_uri:
    external: true 