version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
      - BASE_URI=${BASE_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 